apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: engineering-domain
  title: Engineering Domain
spec:
  owner: bcgdv
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: engineering-system
  title: GridInit
spec:
  owner: bcgdv
  domain: GridStack
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: devportal
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: bcgdv
  system: engineering-system
  lifecycle: experimental
