apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: bcg-engineering-team
  description: BCG Engineering Team
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: bcg-engineering-team@example.com
    picture: https://avatars.dicebear.com/api/initials/bcg-engineering-team@example.com%40example.com.svg?background=%23fff
  parent: backstage
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: bcg-engineering-team-admin
spec:
  profile:
    # Intentional no displayName for testing
    email: bcg-engineering-team-admin@example.com
    picture: https://avatars.dicebear.com/api/initials/bcg-engineering-team-admin%40example.com.svg?background=%23fff
  memberOf: [bcg-engineering-team]
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: engineering-domain
  title: Engineering Domain
spec:
  owner: bcg-engineering-team
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: engineering-system
  title: Engineering System
spec:
  owner: bcg-engineering-team
  domain: engineering-domain
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: devportal
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: bcg-engineering-team
  system: engineering-system
  lifecycle: experimental
